use crate::capture::PasteboardMarkers;

pub fn read_pasteboard_markers() -> PasteboardMarkers {
    #[cfg(target_os = "macos")]
    {
        read_pasteboard_markers_macos()
    }

    #[cfg(not(target_os = "macos"))]
    {
        PasteboardMarkers::default()
    }
}

#[cfg(target_os = "macos")]
fn read_pasteboard_markers_macos() -> PasteboardMarkers {
    use cocoa::base::{id, nil};
    use objc::{class, msg_send, sel, sel_impl};

    std::panic::catch_unwind(|| unsafe {
        let pasteboard: id = msg_send![class!(NSPasteboard), generalPasteboard];
        if pasteboard == nil {
            return PasteboardMarkers::default();
        }

        PasteboardMarkers {
            is_transient: pasteboard_has_type(pasteboard, "org.nspasteboard.TransientType"),
            is_concealed: pasteboard_has_type(pasteboard, "org.nspasteboard.ConcealedType"),
            is_auto_generated: pasteboard_has_type(
                pasteboard,
                "org.nspasteboard.AutoGeneratedType",
            ),
            is_remote: pasteboard_has_type(pasteboard, "com.apple.is-remote-clipboard"),
            source_bundle_id: pasteboard_string_for_type(pasteboard, "org.nspasteboard.source"),
        }
    })
    .unwrap_or_else(|_| {
        log::error!("[PasteboardMarkers] 读取 macOS pasteboard marker 失败，回退为 no-op");
        PasteboardMarkers::default()
    })
}

#[cfg(target_os = "macos")]
unsafe fn pasteboard_has_type(pasteboard: cocoa::base::id, pasteboard_type: &str) -> bool {
    use cocoa::base::{id, nil, BOOL, YES};
    use cocoa::foundation::NSString;
    use objc::{msg_send, sel, sel_impl};

    let types: id = msg_send![pasteboard, types];
    if types == nil {
        return false;
    }

    let pasteboard_type_ns = NSString::alloc(nil).init_str(pasteboard_type);
    let contains: BOOL = msg_send![types, containsObject: pasteboard_type_ns];
    contains == YES
}

#[cfg(target_os = "macos")]
unsafe fn pasteboard_string_for_type(
    pasteboard: cocoa::base::id,
    pasteboard_type: &str,
) -> Option<String> {
    use cocoa::base::{id, nil};
    use cocoa::foundation::NSString;
    use objc::{msg_send, sel, sel_impl};

    let pasteboard_type_ns = NSString::alloc(nil).init_str(pasteboard_type);
    let value: id = msg_send![pasteboard, stringForType: pasteboard_type_ns];
    if value == nil {
        return None;
    }

    let value_c_str: *const i8 = msg_send![value, UTF8String];
    if value_c_str.is_null() {
        return None;
    }

    std::ffi::CStr::from_ptr(value_c_str)
        .to_str()
        .ok()
        .map(|value| value.to_string())
}
